import "./styles.css";
import "animate.css";
import openDashboard from "./scripts/dashboard";
import addTask from "./scripts/addTask";
import { loadTasksFromLocalStorage } from "./scripts/storage";
const dashboardBtn = document.querySelector("#dashboard-btn");
const addBtn = document.querySelector("#add-btn");
dashboardBtn.addEventListener("click", openDashboard);
addBtn.addEventListener("click", addTask);
document.addEventListener("DOMContentLoaded", loadTasksFromLocalStorage);
